Repository UXMUnderGraduate/22-S-Front, pull requests merged in 2022-08, with the labels that each got.

#19 feat: "loginPage"
  src/page/LoginPage.jsx
Labels: 👀리뷰 필요, 지현, 👨🏻‍💻개발중

#25 Register #6
  package-lock.json
  package.json
  src/page/RegisterPage.jsx
Labels: 지현

#33 Design : 업로드페이지 테마 #9
  src/page/UploadPage.jsx
Labels: 지현, 👨🏻‍💻개발중

#36 Feat : 프로필페이지 추가
  package-lock.json
  package.json
  src/components/MyProfile.jsx
  src/page/LoginPage.jsx
  src/page/ProfilePage.jsx
  src/page/RegisterPage.jsx
Labels: 민수, 👨🏻‍💻개발중

#40 Feat : 약관추가 #12
  src/components/Header.jsx
Labels: 민수, ✅완료

#41 feat:회원가입 axios, 비밀번호 view수정 #5
  src/page/RegisterPage.jsx
Labels: 지현, ✅완료

#44 Upload #9
  src/page/UploadPage.jsx
Labels: 지현, 👨🏻‍💻개발중

#47 수정
  package-lock.json
  package.json
  src/page/LoginPage.jsx
  src/page/RegisterPage.jsx
  src/page/UploadPage/TOSAlert.jsx
  src/page/UploadPage/UploadPage.jsx
Labels: 지현, 👨🏻‍💻개발중

#48 Login
  src/page/LoginPage.jsx
  src/page/RegisterPage.jsx
Labels: 지현, ✅완료

#52 feat: Web3 연동
  config-overrides.js
  package-lock.json
  package.json
  src/assets/contracts_SellerContract_sol_SellerContract.json
  src/assets/contracts_SellerContract_sol_SellerContract.txt
  src/assets/contracts_SettlementContract_sol_SettlementContract.json
  src/assets/contracts_SettlementContract_sol_SettlementContract.txt
  src/polyfill.js
  src/services/contract.js
  src/services/metamask.js
Labels: ✅완료

#53 feat : 업로드페이지 수정
  src/page/UploadPage/UploadPage.jsx
Labels: 지현, 👨🏻‍💻개발중

#61 Upload #9
  src/page/UploadPage.jsx
Labels: 지현, 👨🏻‍💻개발중
