Repository UXMUnderGraduate/22-S-Front, pull requests merged in 2022-12, with the labels that each got.

#106 Fix: 음원 업로드시 저작권자 중복 입력시 발생 오류 해결 및 구매시 backend post
  src/page/SongInfoPage.jsx
  src/page/UploadPage.jsx
Labels: ✅완료

#107 feat: 업로드 페이지 수정
  src/page/UploadPage.jsx
Labels: 지현

#108 Fix : BE api 수정
  README.md
  src/index.js
  src/page/BoardPage.jsx
  src/reportWebVitals.js
  src/setupTests.js
Labels: 🐞버그, 👀리뷰 필요, 민수, ✅완료
